spring:
  profiles:
    include:
        - database
        - keycloak
        - security
        - jwt
server:
  port: ${SERVER_PORT:8081}

# Logging configuration for detailed request tracking
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: DEBUG
    org.springframework.web.servlet.handler: DEBUG
    org.springframework.web.filter: DEBUG
    com.bitetogether.user: DEBUG
