spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    
    properties:
      security-protocol: ${KAFKA_SECURITY_PROTOCOL:SSL}
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_SSL_KEYSTORE_LOCATION:classpath:client.keystore.p12}
          password: ${KAFKA_SSL_KEYSTORE_PASSWORD}
        truststore:
          type: JKS
          location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:classpath:client.truststore.jks}
          password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD}
        endpoint-identification-algorithm: ""
      
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    topic:
      user-events: ${USER_EVENTS_TOPIC:user-events}
      conversation-events: ${CONVERSATION_EVENTS_TOPIC:conversation-events}
