spring:
  profiles:
    active:
        - database
        - firebase
        - jwt
        - kafka
        - openapi
        - redis
        - security
        - openfeign
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 8MB
server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: read_only

logging:
  level:
    org.springframework.security: DEBUG